# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4826a351bda1ee0bb0a699d269c209069f57a6e129b1ff03ba6a18dd5a7cd206ac000919e01499e63008d6eb561d922c2b8f295a3f6e90863c1ed9c7baa09b34

test:
  secret_key_base: 9756cd3c587db5e371c2dd15efa9b6e0d2027c8bd58a553145d5d925e5da8adf529c2b6a44935a5907687e0d0b778a7aa6f85ee3ea0cc2e1e7016a4ff4e9f528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
